
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Luiz Bataioli
 */
public class TelaCadastroClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroClientes
     */
    public TelaCadastroClientes() {
        initComponents();
        habilitarBotoes(false);
        botoesEdicao(false);
        habilitarCaixas(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCabecalho = new javax.swing.JPanel();
        jlbTitulo = new javax.swing.JLabel();
        jlbIcone = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnDados = new javax.swing.JPanel();
        lblTituloCliente = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblTelefoneUsuario = new javax.swing.JLabel();
        lblEmailUsuario = new javax.swing.JLabel();
        jtfNomeClienteDigitado = new javax.swing.JTextField();
        jtfTelefoneDigitado = new javax.swing.JTextField();
        jtfEmailClienteDigitado = new javax.swing.JTextField();
        jtfIdadePetDigitada = new javax.swing.JTextField();
        lblIdadePet = new javax.swing.JLabel();
        lblRacaPet = new javax.swing.JLabel();
        jtfRacaPetDigitado = new javax.swing.JTextField();
        jtfNomePetDigitado = new javax.swing.JTextField();
        lblNomePet = new javax.swing.JLabel();
        lblTipoPet = new javax.swing.JLabel();
        jtfTipoPetDigitado = new javax.swing.JTextField();
        lblTituloDadosPet = new javax.swing.JLabel();
        lblTipoServico = new javax.swing.JLabel();
        cbxTipoServico = new javax.swing.JComboBox<>();
        jspClientesCadastrados = new javax.swing.JScrollPane();
        jtClientesCadastrados = new javax.swing.JTable();
        jpnBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConcluirServico = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jlbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlbTitulo.setText("Cadastro de Clientes:");

        jlbIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pet-shop.png"))); // NOI18N

        javax.swing.GroupLayout jpnCabecalhoLayout = new javax.swing.GroupLayout(jpnCabecalho);
        jpnCabecalho.setLayout(jpnCabecalhoLayout);
        jpnCabecalhoLayout.setHorizontalGroup(
            jpnCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jlbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnCabecalhoLayout.setVerticalGroup(
            jpnCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCabecalhoLayout.createSequentialGroup()
                .addGroup(jpnCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(jpnCabecalhoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jlbTitulo)))
                .addContainerGap())
        );

        lblTituloCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCliente.setText("Dados do cliente:");

        lblNomeUsuario.setText("Nome:");

        lblTelefoneUsuario.setText("Telefone:");

        lblEmailUsuario.setText("E-mail:");

        lblIdadePet.setText("Idade:");

        lblRacaPet.setText("Raça:");

        lblNomePet.setText("Nome:");

        lblTipoPet.setText("Tipo:");

        lblTituloDadosPet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloDadosPet.setText("Dados do pet:");

        lblTipoServico.setText("Tipo de serviço:");

        cbxTipoServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banho", "Tosa", "Hospedagem", "Vacinação" }));

        javax.swing.GroupLayout jpnDadosLayout = new javax.swing.GroupLayout(jpnDados);
        jpnDados.setLayout(jpnDadosLayout);
        jpnDadosLayout.setHorizontalGroup(
            jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDadosLayout.createSequentialGroup()
                .addComponent(lblNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeClienteDigitado))
            .addGroup(jpnDadosLayout.createSequentialGroup()
                .addComponent(lblTelefoneUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTelefoneDigitado))
            .addGroup(jpnDadosLayout.createSequentialGroup()
                .addComponent(lblEmailUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfEmailClienteDigitado))
            .addGroup(jpnDadosLayout.createSequentialGroup()
                .addComponent(lblTipoServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 547, Short.MAX_VALUE))
            .addGroup(jpnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDadosLayout.createSequentialGroup()
                        .addComponent(lblTipoPet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTipoPetDigitado))
                    .addGroup(jpnDadosLayout.createSequentialGroup()
                        .addComponent(lblNomePet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomePetDigitado))
                    .addGroup(jpnDadosLayout.createSequentialGroup()
                        .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRacaPet)
                            .addComponent(lblIdadePet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfRacaPetDigitado)
                            .addComponent(jtfIdadePetDigitada)))
                    .addGroup(jpnDadosLayout.createSequentialGroup()
                        .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloCliente)
                            .addComponent(lblTituloDadosPet))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnDadosLayout.setVerticalGroup(
            jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeUsuario)
                    .addComponent(jtfNomeClienteDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneUsuario)
                    .addComponent(jtfTelefoneDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailUsuario)
                    .addComponent(jtfEmailClienteDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoServico)
                    .addComponent(cbxTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloDadosPet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoPet)
                    .addComponent(jtfTipoPetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomePet)
                    .addComponent(jtfNomePetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRacaPet)
                    .addComponent(jtfRacaPetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdadePet)
                    .addComponent(jtfIdadePetDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jpnDados);

        jtClientesCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Telefone", "E-mail", "Atendimento", "Serviço", "Tipo pet", "Nome Pet", "Raça", "Idade", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtClientesCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesCadastradosMouseClicked(evt);
            }
        });
        jtClientesCadastrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtClientesCadastradosKeyReleased(evt);
            }
        });
        jspClientesCadastrados.setViewportView(jtClientesCadastrados);

        jTabbedPane1.addTab("Clientes", jspClientesCadastrados);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnConcluirServico.setText("Concluir");
        btnConcluirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirServicoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnBotoesLayout = new javax.swing.GroupLayout(jpnBotoes);
        jpnBotoes.setLayout(jpnBotoesLayout);
        jpnBotoesLayout.setHorizontalGroup(
            jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConcluirServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addGap(111, 111, 111)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addGap(22, 22, 22))
        );
        jpnBotoesLayout.setVerticalGroup(
            jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBotoesLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnConcluirServico)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnNovo)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        String nomeCliente = jtfNomeClienteDigitado.getText();
        String telefoneCliente = jtfTelefoneDigitado.getText();
        String emailCliente = jtfEmailClienteDigitado.getText();
        String tipoPet = jtfTipoPetDigitado.getText();
        String nomePet = jtfNomePetDigitado.getText();
        String racaPet = jtfRacaPetDigitado.getText();
        String idadePet = jtfIdadePetDigitada.getText();
        String tipoServico = cbxTipoServico.getSelectedItem().toString();
        String status = "Em andamento";
        
        
        int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente concluir o cadastro de " + nomeCliente + "?", 
               "Conrimação de cadastro", 
               JOptionPane.YES_OPTION);
        
       if(resposta == 0){
           
           DefaultTableModel dtmContatos = (DefaultTableModel) jtClientesCadastrados.getModel();
           Object[] dados = {nomeCliente, telefoneCliente, emailCliente, FormatacaoData(), tipoServico, tipoPet, nomePet, racaPet, idadePet, status};
           dtmContatos.addRow(dados);
           
           JOptionPane.showMessageDialog(null, "O cadastro foi concluído!");
           habilitarBotoes(false);
           habilitarCaixas(false);
           apagarTudo();
       }else{
           JOptionPane.showMessageDialog(null, "Operação cancelada");
           
       }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jtClientesCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesCadastradosMouseClicked
        if(jtClientesCadastrados.getSelectedRow() != -1){
            
            int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente editar algo neste cliente? ", 
               "Confirmação de edição", 
               JOptionPane.YES_NO_OPTION);
            
            if(resposta == JOptionPane.YES_OPTION){
            
                jtfNomeClienteDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 0).toString());
                jtfTelefoneDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 1).toString());
                jtfEmailClienteDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 2).toString());
                cbxTipoServico.setSelectedItem(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 4).toString());
                jtfTipoPetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 5).toString());
                jtfNomePetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 6).toString());
                jtfRacaPetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 7).toString());
                jtfIdadePetDigitada.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 8).toString());
                habilitarBotoes(false);
                botoesEdicao(true);
                habilitarCaixas(true);
                
            }else{
                JOptionPane.showMessageDialog(null, "Operação cancelada!");
            }
            

        }
    }//GEN-LAST:event_jtClientesCadastradosMouseClicked

    private void btnConcluirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirServicoActionPerformed
        
        if(jtClientesCadastrados.getSelectedRow() != -1){
            
            int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente concluir este serviço?", 
               "Conrimação de salvamento", 
               JOptionPane.YES_OPTION);
        
       if(resposta == 0){
           
           jtClientesCadastrados.setValueAt("Concluido!", jtClientesCadastrados.getSelectedRow(), 9);
           botoesEdicao(false);
           habilitarCaixas(false);
           apagarTudo();
           
       }else{
           JOptionPane.showMessageDialog(null, "Cancelada");
       }
            

        }
    }//GEN-LAST:event_btnConcluirServicoActionPerformed

    private void jtClientesCadastradosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClientesCadastradosKeyReleased
        if(jtClientesCadastrados.getSelectedRow() != -1){
            jtfNomeClienteDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 0).toString());
            jtfTelefoneDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 1).toString());
            jtfEmailClienteDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 2).toString());
            cbxTipoServico.setSelectedItem(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 4).toString());
            jtfTipoPetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 5).toString());
            jtfNomePetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 6).toString());
            jtfRacaPetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 7).toString());
            jtfIdadePetDigitada.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 8).toString());
        }
                   
    }//GEN-LAST:event_jtClientesCadastradosKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(jtClientesCadastrados.getSelectedRow() != -1){
            
            DefaultTableModel dtmContatos = (DefaultTableModel) jtClientesCadastrados.getModel();
            
            int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente editar este contato?", 
               "Conrimação de salvamento", 
               JOptionPane.YES_OPTION);
        
       if(resposta == 0){
           
            jtClientesCadastrados.setValueAt(jtfNomeClienteDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 0);
            jtClientesCadastrados.setValueAt(jtfTelefoneDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 1);
            jtClientesCadastrados.setValueAt(jtfEmailClienteDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 2);
            jtClientesCadastrados.setValueAt( cbxTipoServico.getSelectedItem(), jtClientesCadastrados.getSelectedRow(), 4);
            jtClientesCadastrados.setValueAt(jtfTipoPetDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 5);
            jtClientesCadastrados.setValueAt(jtfNomePetDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 6);
            jtClientesCadastrados.setValueAt(jtfRacaPetDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 7);
            jtClientesCadastrados.setValueAt(jtfIdadePetDigitada.getText(), jtClientesCadastrados.getSelectedRow(), 8);
            apagarTudo();
            botoesEdicao(false);
            habilitarCaixas(false);
           
           JOptionPane.showMessageDialog(null, "O contato foi editado!");
       }else{
           JOptionPane.showMessageDialog(null, "Cancelada");
       }
            
            
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(jtClientesCadastrados.getSelectedRow() != -1){
            
            int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente excluir esse contato?", 
               "Confirmação de exclusão", 
               JOptionPane.YES_OPTION);
            
            if(resposta == 0){
            
            DefaultTableModel dtmContatos = (DefaultTableModel) jtClientesCadastrados.getModel();
            dtmContatos.removeRow(jtClientesCadastrados.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Cliente excluido com sucesso!");
                botoesEdicao(false);
                habilitarCaixas(false);
                apagarTudo();
            }else{
                JOptionPane.showMessageDialog(null, "Operação cancelada!");
            }
            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        habilitarBotoes(true);
        habilitarCaixas(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //File relatorioTxt = new File("C:/Users/Luiz Bataioli/Downloads/relatorios/relatorio.txt");
        DefaultTableModel model = (DefaultTableModel) jtClientesCadastrados.getModel();

        int rowCount = model.getRowCount();
        int colCount = model.getColumnCount();

        StringBuilder content = new StringBuilder();

        for (int i = 0; i < rowCount; i++) {
            for (int j = 0; j < colCount; j++) {
                content.append(model.getValueAt(i, j));
                content.append("\t"); // Adiciona uma tabulação entre as colunas
            }
            content.append("\n"); // Adiciona uma nova linha entre as linhas
        }

        try (PrintWriter writer = new PrintWriter(new FileWriter("C:/Users/Luiz Bataioli/Downloads/relatorios/relatorio.txt"))) {
            writer.println(content.toString());
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void apagarTudo(){
        jtfEmailClienteDigitado.setText("");
        jtfIdadePetDigitada.setText("");
        jtfNomeClienteDigitado.setText("");
        jtfNomePetDigitado.setText("");
        jtfRacaPetDigitado.setText("");
        jtfTelefoneDigitado.setText("");
        jtfTipoPetDigitado.setText("");
        
    }
    
    private void habilitarBotoes(boolean setReset){
        btnCancelar.setEnabled(setReset);
        btnSalvar.setEnabled(setReset);
    }
    
    private void botoesEdicao(boolean setReset){
        btnConcluirServico.setEnabled(setReset);
        btnEditar.setEnabled(setReset);
        btnExcluir.setEnabled(setReset);
    }
    private void habilitarCaixas(boolean setReset){
        jtfEmailClienteDigitado.setEditable(setReset);
        jtfIdadePetDigitada.setEditable(setReset);
        jtfNomeClienteDigitado.setEditable(setReset);
        jtfNomePetDigitado.setEditable(setReset);
        jtfRacaPetDigitado.setEditable(setReset);
        jtfTelefoneDigitado.setEditable(setReset);
        jtfTipoPetDigitado.setEditable(setReset);
        cbxTipoServico.setEnabled(setReset);
    }
    
    private String FormatacaoData() {
        
        Date dataAtual = new Date();

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

        String dataFormatada = formato.format(dataAtual);

        return(dataFormatada);
    
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConcluirServico;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxTipoServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbIcone;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JPanel jpnBotoes;
    private javax.swing.JPanel jpnCabecalho;
    private javax.swing.JPanel jpnDados;
    private javax.swing.JScrollPane jspClientesCadastrados;
    private javax.swing.JTable jtClientesCadastrados;
    private javax.swing.JTextField jtfEmailClienteDigitado;
    private javax.swing.JTextField jtfIdadePetDigitada;
    private javax.swing.JTextField jtfNomeClienteDigitado;
    private javax.swing.JTextField jtfNomePetDigitado;
    private javax.swing.JTextField jtfRacaPetDigitado;
    private javax.swing.JTextField jtfTelefoneDigitado;
    private javax.swing.JTextField jtfTipoPetDigitado;
    private javax.swing.JLabel lblEmailUsuario;
    private javax.swing.JLabel lblIdadePet;
    private javax.swing.JLabel lblNomePet;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblRacaPet;
    private javax.swing.JLabel lblTelefoneUsuario;
    private javax.swing.JLabel lblTipoPet;
    private javax.swing.JLabel lblTipoServico;
    private javax.swing.JLabel lblTituloCliente;
    private javax.swing.JLabel lblTituloDadosPet;
    // End of variables declaration//GEN-END:variables
}
